### ISSUE TITLE
cerbero: Mac version 11.3.1 not supported

### ISSUE THREAD

**Issue by rene-dohan** [atsushieno/fluidsynth-midi-service-j#23]
I tried to build but looks like cebrero cannot build anymore

```
  File "/Users/renetik/Development/fluidsynth-midi-service-j-1/external/fluidsynth/doc/android/external/cerbero/cerbero/utils/__init__.py", line 353, in system_info
    raise FatalError("Mac version %s not supported" % ver)
cerbero.errors.FatalError: Fatal Error: Mac version 11.3.1 not supported
make[1]: *** [prepare] Error 1
make: *** [prepare-fluidsynth] Error 2
```

**Comment by atsushieno** [comment]
That's not very surprising... I'm quite unsure if the upstream Cerbero itself supports macOS 11, also not sure if I would support Cerbero based project builder, as it is getting deprecated at Fluidsynth itself now. Android builds were rewritten, and it's not working as expected and we have been working on build fixes these days.

**Comment by rene-dohan** [comment]
@atsushieno I would like to implement some c++ code to enable recording of audio stream in oboe driver...  I was able to build it before so was thinking based on some advises form oboe dev to extend oboe driver code to enable that by myself. Looks like now I cannot do that. Do you have any quick ideas about that ? Thanks.

**Comment by atsushieno** [comment]
You should be heading to the upstream Fluidsynth project and check the latest build scripts and/or artifacts. If Cerbero does not work, there is no reason to stick to it. Also, this repository is for my **application** project. There is nothing you can contribute to Oboe driver here. I'm quite unsure how audio-recording capability plays any role there though (but this issue is not to hear about that details, should be discussed at Fluidsynth/fluidsynth).
